name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List and Read files
          run: |
            echo "myf irst github actions job"
            ls -la
            cat README.md
        
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Hello, GitHub Actions!" >> dragon.txt
#      # - name: Welcome message
#          run: echo "my first github actions job"

 #       - name: List files
 #         run: ls
          


